sonar.organization=volsch
sonar.projectKey=volsch_python-md24de
sonar.projectName=python-md24de

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
